spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    database-platform: H2
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
        use_sql_comments: true